{% set version = "0.1.90" %}

package:
  name: jinja-lsp
  version: {{ version }}

source:
  url: https://github.com/uros-5/jinja-lsp/archive/v{{ version }}.tar.gz
  sha256: bb61303c318bee8c9c30e23dc1cf618192d1de87f6b2f9acb92b2e358a45e4cf

build:
  number: 1

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - jinja-lsp &  # [not win]
    - exe_pid=$!  # [not win]
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM  # [not win]
    - start /b jinja-lsp   # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]
    - taskkill /F /im jinja-lsp.exe  # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]

about:
  home: https://github.com/uros-5/jinja-lsp
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Language Server for jinja
  dev_url: https://github.com/uros-5/jinja-lsp

extra:
  recipe-maintainers:
    - danielnachun
