{% set name = "jinja-lsp" %}
{% set version = "0.1.81" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/uros-5/jinja-lsp/archive/v{{ version }}.tar.gz
  sha256: 054a098c75a243c4f7dd91b005fd37b076979094a0aaf3a6c35c3ac2920e9931

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - jinja-lsp &  # [not win]
    - exe_pid=$!  # [not win]
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM  # [not win]
    - start /b jinja-lsp   # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]
    - taskkill /F /im jinja-lsp.exe  # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]

about:
  home: https://github.com/uros-5/jinja-lsp
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Language Server for jinja
  dev_url: https://github.com/uros-5/jinja-lsp

extra:
  recipe-maintainers:
    - danielnachun
